namespace Auraxis.Net.Models
{
    public class SingleCharacterById { }
    public class Character { }
    public class CharactersWeaponStat { }
    public class CharactersWeaponStatByFaction { }
    public class Outfit { }
    public class OutfitMember { }
    public class CharactersFriend { }
    public class Leaderboard { }
    public class CharactersLeaderboard { }
    public class CharactersEventGrouped { }
    public class CharactersEvent { }
    public class Event { }

    // No resolves
    public class CharacterName { }
    public class CharactersAchievement { }
    public class CharactersCurrency { }
    public class CharactersDirective { }
    public class CharactersDirectiveObjective { }
    public class CharactersDirectiveTier { }
    public class CharactersDirectiveTree { }
    public class CharactersSkill { }
    public class CharactersStat { }
    public class CharactersStatByFaction { }
    public class CharactersStatHistory { }
    public class WorldStatHistory { }
    public class CharactersItem { }
    public class Ability { }
    public class AbilityType { }
    public class Achievement { }
    public class ArmorFacing { }
    public class ArmorInfo { }
    public class Currency { }
    public class Directive { }
    public class DirectiveTier { }
    public class DirectiveTree { }
    public class DirectiveTreeCategory { }
    public class Effect { }
    public class EffectType { }
    public class EmpireScores { }
    public class Experience { }
    public class ExperienceRank { }
    public class FacilityLink { }
    public class FacilityType { }
    public class Faction { }
    public class FireGroup { }
    public class FireGroupToFireMode { }
    public class FireMode { }
    public class FireMode2 { }
    public class FireModeToProjectile { }
    public class FireModeType { }
    public class Image { }
    public class ImageSet { }
    public class ImageSetDefault { }
    public class Item { }
    public class ItemAttachment { }
    public class ItemCategory { }
    public class ItemProfile { }
    public class ItemToWeapon { }
    public class ItemType { }
    public class Loadout { }
    public class MapHex { }
    public class MapRegion { }
    public class MarketingBundle { }
    public class MarketingBundleItem { }
    public class MarketingBundleWith1Item { }
    public class MetagameEvent { }
    public class MetagameEventState { }
    public class Objective { }
    public class ObjectiveSetToObjective { }
    public class ObjectiveType { }
    public class PlayerState { }
    public class PlayerStateGroup { }
    public class PlayerStateGroup2 { }
    public class Profile { }
    public class Profile2 { }
    public class ProfileArmorMap { }
    public class ProfileResistMap { }
    public class Projectile { }
    public class ProjectileFlightType { }
    public class Region { }
    public class ResistInfo { }
    public class ResistType { }
    public class ResourceType { }
    public class Reward { }
    public class RewardGroupToReward { }
    public class RewardSetToRewardGroup { }
    public class RewardType { }
    public class Skill { }
    public class SkillCategory { }
    public class SkillLine { }
    public class SkillSet { }
    public class TargetType { }
    public class Title { }
    public class Vehicle { }
    public class VehicleAttachment { }
    public class VehicleFaction { }
    public class VehicleSkillSet { }
    public class Weapon { }
    public class WeaponAmmoSlot { }
    public class WeaponDatasheet { }
    public class WeaponToAttachment { }
    public class WeaponToFireGroup { }
    public class Zone { }
    public class ZoneEffect { }
    public class ZoneEffectType { }
    public class CharactersWorld { }
    public class World { }
    public class OutfitMemberExtended { }
    public class OutfitTank { }
    public class CharactersOnlineStatus { }
    public class Map { }
    public class WorldEvent { }
}
